name: Windows Unity Build

on:
  push:
    branches:
    - builds-win

jobs:

  build:
    name: Build Windows Unity Game
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          dest: build/Windows

      - name: Check Build Directory Contents
        run: ls -R build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-windows
          path: build/Windows

      - name: Zip Build
        uses: vimtor/action-zip@v1
        with:
          files: build/Windows
          dest: build/Windows.zip
          
      - name: g-drive-upload
        uses: logickoder/google-drive-upload@1.0.0
        with:
            credentials: ${{secrets.GOOGLEAUT}}
            filename: build/Windows.zip
            folderId: 1bzqSl0J_EGg2PuOj2FRobfU0h4Xc93f1