name: Unity Build

#Run this when a branch gets pushed
on:
  push:
    branches:
    - builds-win

jobs:
  build:
    name: Build Unity Game

    #the build OS
    runs-on: windows-latest

    steps:
      #step 1: checkout
      - name: Checkout repository
        uses: actions/checkout@v3

        # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      #step 2: setup unity
      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          version: 2022.3.25f1


      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        with:
          unityVersion: 2022.3.25f1

      #step 3: build
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          
      # Step 4: Install gdrive tool
      - name: Install gdrive
        run:
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o gdrive.tar.gz https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64
          chmod +x gdrive-linux-x64
          sudo mv gdrive-linux-x64 /usr/local/bin/gdrive

      # Step 5: Authenticate gdrive with Service Account
      - name: Authenticate with Google Drive
        run:
          echo "${{ secrets.GOOGLEAUT}}" > service_account.json
          gdrive about -s service_account.json

      # Step 6: Upload build artifact to Google Drive
      - name: Upload to Google Drive
        run: 
          gdrive upload --service-account service_account.json --parent <your-google-drive-folder-id> build/
