name: Unity Build

#Run this when a branch gets pushed
on:
  push:
    branches:
    - builds-win

jobs:
  build:
    name: Build Unity Game

    #the build OS
    runs-on: windows-latest

    steps:
      #step 1: checkout
      - name: Checkout repository
        uses: actions/checkout@v3

        # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64


      - name: Zip Build
        uses: vimtor/action-zip@v1
        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
        with:
          files: build/Windows/*
          dest: build/cgs-${{ Windows }}.zip
          
      - name: g-drive-upload
  # You may pin to the exact commit or the version.
  # uses: logickoder/google-drive-upload@85187aba3b917357f61166c1ed2b50c6f261fd94
        uses: logickoder/google-drive-upload@1.0.0
        with:
    # the service account credentials
            credentials: ${{secrets.GOOGLEAUT}}
    # the name of the file you want to upload. Wildcards can be used to upload more than one file
            filename: build/Windows.zip
    # the Id of the parent folder you want to upload the file in
            folderId: 1bzqSl0J_EGg2PuOj2FRobfU0h4Xc93f1
          
