name: Unity Build

#Run this when a branch gets pushed
on:
  push:
    branches:
    - builds-win

jobs:
  build:
    name: Build Unity Game

    #the build OS
    runs-on: windows-latest

    steps:
      #step 1: checkout
      - name: Checkout repository
        uses: actions/checkout@v3

        # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          
    #Step 4: Install gdrive tool
      - name: Install gdrive
        run: |
          Invoke-WebRequest -Uri https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-windows-x64.exe -OutFile gdrive.exe
          Move-Item .\gdrive.exe "C:\Program Files\gdrive.exe"

      # Step 5: Authenticate gdrive with Service Account
      - name: Authenticate with Google Drive
        run:
          echo "${{ secrets.GOOGLEAUT}}" > service_account.json
          gdrive about -s service_account.json

      # Step 6: Upload build artifact to Google Drive
      - name: Upload to Google Drive
        run: 
          gdrive upload --service-account service_account.json --parent <your-google-drive-folder-id> build/
